[unstable]
# Esto le dice a cargo que debe recompilar las bibliotecas corey . compiler_builtins.
# Este último es obligatorio porque es una dependencia de core.
build-std = ["core", "compiler_builtins"]
#Habilitamos las funciones para manejo de memoría que trae builtins-mem
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-sav_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"